### ISSUE TITLE
Reduce the size of sended data to confd

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/backend#118]
reduce the size by removing all the null variables. these variables are not written into confd anyway and json file that is sent can get rid of these data

**Comment by miroslavKovacPantheon** [comment]
also because of the new confd 7 we are using restconf interface instead of old rest and it does not allow sending json data with null objects in it

**Comment by evyncke** [comment]
About Confd 7, is it the latest version from Cisco ?

**Comment by miroslavKovacPantheon** [comment]
yes that is correct
