### ISSUE TITLE
Outdated CondD version ?

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/backend#133]
Per https://github.com/YangCatalog/backend/issues/36#issuecomment-669547581

It seems that YC.O uses an outdated version of confd (the original poster is a Cisco colleague working notably with NSO)

**Comment by miroslavKovacPantheon** [comment]
This was updated to confd-7.3.1.linux.x86_64.installer.bin.. early this year. The other issues was old one from two years ago. I would say this is resolved and close this but if you have any other questions just let me know. I ll keep it open for several more days. Feel free to close it.

**Comment by miroslavKovacPantheon** [comment]
Updated to 7.5
