### ISSUE TITLE
Keep records of whether the file has been modified

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/backend#183]
**Current state:**
In the runCapabilities.py script there is a _save_modification_date_ argument.
If set to True then it will create a .txt file with modification date of currently parsed .xml file.
It will also check if file was modified from last time if not it will skip it, which means no capability script is run

**Possible improvement:**
- Creating a class that will implement this functionality, but will store modification dates not only for .xml files but also .yang.
- DO NOT create .txt file with modification date information stored in it, but instead create one json file, with key - value pairs.
- Key will be name of the file, value will be hashed content of the file.
- This information about changes in the content of the file will then be used in other scripts.
- If the content of the file have not changed, the processing of this file may be skipped.

**Example of fileModifications.json file:**
```
{
	"cisco-xr-701-capabilities-ncs5k.xml": "26e22cd8ea36f2cc",
	"cisco-xr-701-Cisco-IOS-XR-wd-oper.yang": "f9dff6cbdc13ee0e"
	
	... OR ...
	
	"/var/yang/nonietf/yangmodels/yang/vendor/cisco/xr/701/capabilities-ncs5k.xml": "26e22cd8ea36f2cc",
	"/var/yang/nonietf/yangmodels/yang/vendor/cisco/xr/701/Cisco-IOS-XR-wd-oper.yang": "f9dff6cbdc13ee0e"
}
```

**Comment by miroslavKovacPantheon** [comment]
I would rather use the whole path then just a single file name
