### ISSUE TITLE
API documentation link is broken

### ISSUE THREAD

**Issue by wlupton** [YangCatalog/backend#228]
The API documentation link in `README.md` is broken. It's this:

```
[API documentation](www.yangcatalog.org/doc)
```

but the URL scheme is missing; it should be this:

```
[API documentation](https://www.yangcatalog.org/doc)
```

Also, I couldn't see a link to the API documentation page on the main yangcatalog.org home page (there are just a few API examples). Maybe I missed it.

**Comment by wlupton** [comment]
Also I just noticed that the postman link (on the API doc page) is broken:

```
https://yangcatalog.org/downloadables/yangcatalog.postman_collection-v2.json
```

Maybe this should be pointing to `https://yangcatalog.org/downloadables/yangcatalog.postman_collection.json` (which does exist)?

**Comment by miroslavKovacPantheon** [comment]
Thank you @wlupton for submiting this issue. you are right indeed. We will fix these issues momentarily. Collection I am not sure I have to check if it s not the old one. if it is I ll generate a new one in there. We are coming with new APIs as well mainly for yang serach and yangvalidator which were currently only responding with html file which is mostly useless for other developers. UI page is being reworked and therefore we can provide json response as we should.

**Comment by miroslavKovacPantheon** [comment]
changes will be visible after the release. hang tight should be by the end of the next week

**Comment by wlupton** [comment]
Yes, the collection JSON that's there looks a bit of a mixture (more a list of examples). But nevertheless useful!

**Comment by miroslavKovacPantheon** [comment]
yes I want to recreate it with some better defined and described more deeply - maybe url links to docs in each of the endpoint description. also I want to separate it to some folders. create env variables that can be used or changed

**Comment by wlupton** [comment]
Sounds great!
