### ISSUE TITLE
Refactor draftPullLocal.py

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/backend#248]
**Current state:**
Populate script is called using subprocess library. 
If an error occurs while the program is running, it is written to a .txt file.
However, this file is overwritten each time the draftPullLocal script is run, so this information may be lost before it is even checked.
Also, YangModels/yang repository is always cloned into a new folder (randomly generated suffix) making it impossible to use file [content hashing feature](https://github.com/YangCatalog/backend/issues/183).

**Possible improvement:**
- Change this to use ScriptConf of populate script and set all the necessary arguments.
- If an error occurs while the program is running, it will be logged to the appropriate log file.
- During this refactoring, change the directory where YangModels/yang repo is cloned. It should always have the same name.

**Comment by miroslavKovacPantheon** [comment]
Do not clone it if it is yangModels/yang make only pull. Use [this](https://github.com/YangCatalog/backend/blob/master/utility/repoutil.py#L56-L66) to pull latest changes
