### ISSUE TITLE
Remove the Huawei 4 years old YANG modules

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#260]
Hi,

4 years ago, some Huawei YANG modules were inserted in github and, as a consequence, in the YANGcatalog. Those modules are too old/are no relevant any longer/were a test.
Let's start clean by removing those 4 years old YANG modules.
Note: we're working on inserting the YANG modules in github + populating the platform-metadata.json file

Regards, Benoit

**Comment by evyncke** [comment]
Good initiative Benoît

From: bclaise ***@***.***>
Reply-To: YangCatalog/backend ***@***.***>
Date: Tuesday, 27 April 2021 at 12:47
To: YangCatalog/backend ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [YangCatalog/backend] Remove the Huawei 4 years old YANG modules (#260)


Hi,

4 years ago, some Huawei YANG modules were inserted in github and, as a consequence, in the YANGcatalog. Those modules are too old/are no relevant any longer/were a test.
Let's start clean by removing those 4 years old YANG modules.
Note: we're working on inserting the YANG modules in github + populating the platform-metadata.json file

Regards, Benoit
