### ISSUE TITLE
Move global configuration to flask's application.config

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/backend#287]
Currently most of the global configuration resides inside globalConfig.py in the YangCatalogApiGlobalConfig class. This should be migrated over to flask's built in application.config variable.

**Comment by SlavomirMazurPantheon** [comment]
Logger done here https://github.com/YangCatalog/backend/pull/304

**Comment by miroslavKovacPantheon** [comment]
@SlavomirMazurPantheon True and not True at the same time. It looks like our ignorance of flask config is was actually good at this point. Flask config is not reachable in blueprints as it seems and this is why we need something like Global variables as we have. we even created Updating of these variables if change comes from admin ui.

@richardzilincikPantheon Please do a little research on this and make sure that what I am saying is true. Try to find if there is some best practice for saving and config variables through the whole flask application that we are able to use in blueprints as well.

Other thing that should be done in here is fast and easy fix. We are setting the same things in both of the functions. check what is the same and can be merged to one function or even if you cant simply call load_config from init.

contact me with any questions. When done close this with message and open new issue describing what I just said above and reference it to this issue.

**Comment by richardzilincikPantheon** [comment]
The best approach using the global config within blueprints seems to be either accessing the global config directly through flask.current_app, or setting the specific values our blueprint needs from the config in a function registered with flask.Blueprint.record.

**Comment by richardzilincikPantheon** [comment]
The approach I decided to go with is to allow config values to be accessed though attributes by subclassing the config class, as I found this suggested in the flask source code here https://github.com/pallets/flask/blob/53eef278efd59222be406ff5be737f48c92f8313/src/flask/app.py#L235 .
