### ISSUE TITLE
wrong "tree-type" for an old ietf-interface YANG module

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#289]
Hi,

https://yangcatalog.org/yang-search/module_details/?module=ietf-interfaces@2014-05-08, coming from RFC 7223, has the wrong "tree-type" entry. It can't be "nmda", with is for RFC8343. Do we have a tree-type issue with older YANG module revisions?

Regards, Benoit

**Comment by miroslavKovacPantheon** [comment]
this issue is similar to #259

**Comment by bclaise** [comment]
Ok. Opened on April 27th. It's time to fix it now...

**Comment by SlavomirMazurPantheon** [comment]
nmda-compatible tree-type cannot be assigned to module which is not the latest revision of the module.

We've run a script that is currently checking tree-type property for each module in Yang Catalog - starting with IETF modules (which should be all fixed now on PROD) continuing with other modules.
