### ISSUE TITLE
YANG search display issue with extra \n

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#293]
Hi,

I searched for "node-instance-identifier".

I found this:
node-instance-identifier
2018-02-14
typedef
/nacm:node-instance-identifier?typedef
ietf-netconf-acm
Module details for ietf-netconf-acm Module details
Tree View for ietf-netconf-acm Tree View
Impact Analysis for ietf-netconf-acm Impact Analysis
Industry Standard
ietf
ratified
58
passed
Path expression used to represent a special data node, action, or notification instance-identifier string. A node-instance-identifier value is an unrestricted YANG instance-identifier expression. All the same rules as an instance-identifier apply, except that predicates for keys are optional. If a key predicate is missing, then the node-instance-identifier represents all possible server instances for that key. This XML Path Language (XPath) expression is evaluated in the following context: o The set of namespace declarations are those in scope on the leaf element where this type is used. o The set of variable bindings contains one variable, ''USER'', which contains the name of the user of the current session. o The function library is the core function library, but note that due to the syntax restrictions of an instance-identifier, no functions are allowed. o The context node is the root node in the data tree. The accessible tree includes actions and notifications tied to data nodes.

When I click on "node-instance-identifier", i see extra \n

typedef node-instance-identifier {
	type yang:xpath1.0;
	description "Path expression used to represent a special\ndata node, action, or notification instance-identifier\nstring.\n\nA node-instance-identifier value is an\nunrestricted YANG instance-identifier expression.\nAll the same rules as an instance-identifier apply,\nexcept that predicates for keys are optional.  If a key\npredicate is missing, then the node-instance-identifier\nrepresents all possible server instances for that key.\n\nThis XML Path Language (XPath) expression is evaluated in the\nfollowing context:\n\n   o  The set of namespace declarations are those in scope on\n      the leaf element where this type is used.\n\n   o  The set of variable bindings contains one variable,\n      ''USER'', which contains the name of the user of the\n      current session.\n\n   o  The function library is the core function library, but\n      note that due to the syntax restrictions of an\n      instance-identifier, no functions are allowed.\n\n   o  The context node is the root node in the data tree.\n\nThe accessible tree includes actions and notifications tied\nto data nodes.";
}

**Comment by miroslavKovacPantheon** [comment]
Issue transferred to backend. Search is being closed in next following months and all the APIs were already transferred to backend since they have many similar to same functionalities...

**Comment by SlavomirMazurPantheon** [comment]
Problem fixed by changes in this commit: https://github.com/YangCatalog/deployment/commit/247965c1ecf21b22c9c0f0cf846cfb9e8ff19cdd

**NOTE:** Fixed also for HTML special characters like < > & that now display correctly.
Changes deployed to production.
