### ISSUE TITLE
Insane loading of config

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/backend#333]
We are loading config data on many different places throughout the whole [Deployment](https://github.com/YangCatalog/deployment) project. Although we have many git submodules in deployment I would start in backend anyway. Now what is the problem. We call same 4 lines of code on many different places and if someone will ever change the way of loading config they will be probably pissed of at a person who did that (me :/ ).

```
        self.config_path = '/etc/yangcatalog/yangcatalog.conf'
        config = ConfigParser.ConfigParser()
        config._interpolation = ConfigParser.ExtendedInterpolation()
        config.read(self.config_path)
```
these four of lines are loaded in lot of different parts of code and we are using even string path statically which is just insane. We have docker containers and kubernetes pods that are used at the moment. we need to create env variable in both of these setups saying something like

YANGCATALOG_CONFIG_PATH 

and set it up to that path so if someone will decide to change it it will change everywhere the same way.

once that is done we can move the loading these four lines into util module or __init__ module..

**Comment by SlavomirMazurPantheon** [comment]
Good idea - also for running tests in Travis/Github Actions.
We are currently relying on the fact that ConfigParser will not find the configuration file on the path: 
```
/etc/yangcatalog/yangcatalog.conf
```
and will use the fallback values, which we must again set statically in the source code for each script separately.

**Comment by miroslavKovacPantheon** [comment]
PR to check https://github.com/YangCatalog/backend/pull/334

**Comment by richardzilincikPantheon** [comment]
This issue is still relevant, because, as Miroslav pointed out, the config path is still hard coded in repositories other than backend.

> We are loading config data on many different places throughout the whole [Deployment](https://github.com/YangCatalog/deployment) project. Although we have many git submodules in deployment I would start in backend anyway.
