### ISSUE TITLE
Wrong MIME type application/vnd.yang.data+json

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/backend#36]
IANA has specified "application/yang-data+json" which should be used rather than "application/vnd.yang.data+json"

See https://www.iana.org/assignments/media-types/application/yang-data+json

**Comment by miroslavKovacPantheon** [comment]
get request with path http://yangcatalog.org:8008/api/config/catalog/modules/module/ietf-isis,2018-08-09,ietf and content-type and accept as application/yang-data+json gave me the following error:

`
<errors xmlns="http://tail-f.com/ns/tailf-rest-error">
    <error>
        <error-tag>malformed-message</error-tag>
        <error-message>No acceptable mime-type supported. Got: application/yang-data+json ; Should be one of: application/vnd.yang.data+xml, application/vnd.yang.data+json.</error-message>
    </error>
</errors>
`

**Comment by evyncke** [comment]
Oh man... crazy thing...
Leave it like it is, I am closing this issue.

**Comment by rgaglian** [comment]
Hi Eric, Looks like you are using Confd for your RESTCONF API. If you upgrade to a newer version of ConfD, it would align with the standard.

**Comment by miroslavKovacPantheon** [comment]
> 
> 
> Hi Eric, Looks like you are using Confd for your RESTCONF API. If you upgrade to a newer version of ConfD, it would align with the standard.

Yes we were indeed using old version two years ago but it was updated this year and we have started to be using "application/yang-data+json" MIME type

**Comment by evyncke** [comment]
Roque, is there a more recent version than 7.3.1 ?
