### ISSUE TITLE
Missing openconfig-telemetry.yang in the catalog

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#41]
openconfig-telemetry.yang is still a valid YANG module. See https://github.com/openconfig/public/tree/master/release/models/telemetry

It's available in YANG search in old.yangcatalog.org but not yangcatalog.org

**Comment by miroslavKovacPantheon** [comment]
The openconfig telemetry is added to yangcatalog https://yangcatalog.org/yang-search/module_details/?module=openconfig-telemetry
