### ISSUE TITLE
Does the cronjob work correctly?

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#43]
Let's check in a day or two, after this hackathon if the cronjob works fine.
YANGPageMain_2018_11_03.html was not generated.

-rw-rw-r-- 1 yang yang-dev     8783 Nov  1 00:05 IEEEExperimentalYANGPageCompilation_2018_11_01.html
-rw-rw-r-- 1 yang yang-dev    59243 Nov  1 00:06 IEEEStandardYANGPageCompilation_2018_11_01.html
-rw-rw-r-- 1 yang yang-dev  1253381 Nov  1 00:33 IETFDraftYANGPageCompilation_2018_11_01.html
-rw-rw-r-- 1 yang yang-dev      514 Nov  1 00:34 IETFYANGPageMain_2018_11_01.html
-rw-rw-r-- 1 yang yang-dev   618798 Nov  1 00:42 IETFCiscoAuthorsYANGPageCompilation_2018_11_01.html
-rw-rw-r-- 1 yang yang-dev    19883 Nov  1 00:46 YANGPageMain_2018_11_01.html
-rw-rw-r-- 1 yang yang-dev     8783 Nov  2 00:05 IEEEExperimentalYANGPageCompilation_2018_11_02.html
-rw-rw-r-- 1 yang yang-dev    59243 Nov  2 00:06 IEEEStandardYANGPageCompilation_2018_11_02.html
-rw-rw-r-- 1 yang yang-dev  1253381 Nov  2 00:33 IETFDraftYANGPageCompilation_2018_11_02.html
-rw-rw-r-- 1 yang yang-dev      514 Nov  2 00:34 IETFYANGPageMain_2018_11_02.html
-rw-rw-r-- 1 yang yang-dev   618798 Nov  2 00:42 IETFCiscoAuthorsYANGPageCompilation_2018_11_02.html
-rw-rw-r-- 1 yang yang-dev    19883 Nov  2 00:45 YANGPageMain_2018_11_02.html
-rw-rw-r-- 1 yang yang-dev     8783 Nov  3 00:05 IEEEExperimentalYANGPageCompilation_2018_11_03.html
-rw-rw-r-- 1 yang yang-dev    59243 Nov  3 00:06 IEEEStandardYANGPageCompilation_2018_11_03.html
-rw-rw-r-- 1 yang yang-dev  1253381 Nov  3 00:34 IETFDraftYANGPageCompilation_2018_11_03.html
-rw-rw-r-- 1 yang yang-dev      514 Nov  3 00:35 IETFYANGPageMain_2018_11_03.html
-rw-rw-r-- 1 yang yang-dev   618798 Nov  3 00:43 IETFCiscoAuthorsYANGPageCompilation_2018_11_03.html
bclaise@new:/var/yang/backup$

**Comment by miroslavKovacPantheon** [comment]
Is this still valid issue? As far as I can see on the server there is a file YANGPageMain_2019_* for almost all the  days except the ones that we didn t use ietf server
