### ISSUE TITLE
Replace flask_oidc

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/backend#440]
`flask_oidc` depends on the `itsdangerous` package and tries to import functionality that has recently been removed in release 2.1.0. https://itsdangerous.palletsprojects.com/en/2.1.x/changes/
The `flask_oidc` github repo has been last updated in january 2019, so it seems unlikely the issue is going to addressed.

A possible solution is replacing `flask_oidc` with one of the alternative OpenID Connect python implementations listed here: https://openid.net/developers/certified/#RPLibs

**Comment by richardzilincikPantheon** [comment]
In the meantime, perhaps we should lock `itsdangerous` to version 2.0.1?

**Comment by SlavomirMazurPantheon** [comment]
`itsdangerous` temporarily locked to version `2.0.1` in PR: https://github.com/YangCatalog/backend/pull/441

**Comment by richardzilincikPantheon** [comment]
So far `flask_pyoidc` seems like the best alternarive.
https://github.com/zamzterz/Flask-pyoidc
