### ISSUE TITLE
extra \n in leaf description

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#46]
Hi,

See https://www.yangcatalog.org/yang-search/yang_tree/show_node/ietf-interfaces//if:interfaces/if:interface/if:statistics/if:discontinuity-time
description "The time on the most recent occasion at which any one or\nmore of this interface''s counters suffered a\ndiscontinuity.  If no such discontinuities have occurred\nsince the last re-initialization of the local management\nsubsystem, then this node contains the time the local\nmanagement subsystem re-initialized itself.";

This was working fine with the old yangcatalog instance.
https://old.yangcatalog.org/yang-search/show_node.php?module=ietf-interfaces&path=%2Fif%3Ainterfaces%2Fif%3Ainterface%2Fif%3Astatistics%2Fif%3Adiscontinuity-time

Regards, B.

**Comment by miroslavKovacPantheon** [comment]
Done,
Please close the issue if satisfied

Thank you
Miroslav Kovac

**Comment by bclaise** [comment]
thanks.
