### ISSUE TITLE
Module details with different revisions

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#48]
If I select https://www.yangcatalog.org/yang-search/module_details/?module=ietf-interfaces, it provides the latest revision. Now, I select a specific revision (not the latest one) from the pull down menu.
The issue is that the following links always take the latest version:
   Tree View | [Impact Analysis for ietf-interfaces] Impact Analysis | [Yang Suite for ietf-interfaces] Yang Suite
The links should be revision-sensitive

**Comment by evyncke** [comment]
Just to be sure:
1) you select another revision
2) module details are correctly displayed for that version
3) but the links on this page always lead to the latest version

Am I correct ?

**Comment by bclaise** [comment]
yes

**Comment by miroslavKovacPantheon** [comment]
Should be fixed. Please test and let me know if something does not work. Or please close the issue if sattisfied.

**Comment by bclaise** [comment]
From the links, it looks fine.
I took two examples and I faced different issues. 
https://www.yangcatalog.org/yang-search/impact_analysis/ietf-interfaces@2017-08-17
https://www.yangcatalog.org/yang-search/impact_analysis/ietf-interfaces

**Comment by bclaise** [comment]
thanks.
