### ISSUE TITLE
admin email alias for notification

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#50]
Hi,

Implement an admin alias, instead of a hard-coded set of email addresses for yc.o notificatrions, which change as people come and go. This admin alias should be managed by ISOC.
Initially, this mailer should contain the following email addresses: Joe, Benoit, Eric, Miroslav, and I guess Henrik and Robert

Regards, B.

**Comment by xorrkaz** [comment]
I have provided archives and config to Glen and Robert.  Glen has confirmed the receipt of both.  He will start to work on this after the IETF.  At that point, the MX record for yc.o should be switched to the AMSL server, and then an admin alias can be created.

**Comment by miroslavKovacPantheon** [comment]
Is this resolved @xorrkaz?

**Comment by miroslavKovacPantheon** [comment]
This has been resolved and is in config file
