### ISSUE TITLE
Log file should be logs in and not temp_dir

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/backend#52]
Esp in api/receiver.py and utility/messageFactory.py the log files should be in the logs directory

**Comment by evyncke** [comment]
Or rather should not be named 'log.txt' but rather 'stderr.out' or something like that

**Comment by miroslavKovacPantheon** [comment]
log files are changed. MessageFactory keepes the message-log.txt since it is used only as a attachment for cisco spark message. All the log files are moved to /var/yang/tmp directory.
