### ISSUE TITLE
ietf-netconf-subscribed-notifications missing document name

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/backend#53]
https://yangcatalog.org/yang-search/module_details/?module=ietf-netconf-subscribed-notifications
=> no document name.
Therefore, this module shows "document N/A" in https://yangcatalog.org/yang-search/impact_analysis/?modtags=ietf-netconf-client&orgtags=&recursion=&show_dir=both

This module is missing from yangcatalog/private

**Comment by evyncke** [comment]
@bclaise raises this issue in webex team
@miroslavKovacPantheon  also found that one file is missing IETFDraft.json file

**Comment by evyncke** [comment]
Some points:
) `ietf-netconf-subscribed-notifications@2018-08-03.yang` only appears as an example in the appendix  of https://tools.ietf.org/html/draft-ietf-netconf-subscribed-notifications-15#page-70
2) `ietf-subscribed-notifications@2018-08-03.yang` and other revisions appear in https://tools.ietf.org/html/draft-ietf-netconf-subscribed-notifications-15#page-34 and https://tools.ietf.org/html/draft-ietf-netconf-subscribed-notifications-22#page-35

so the ietf-netconf-subscribed-notifications module has a single revision in an expired draft...

**Comment by evyncke** [comment]
And when fetching the latest drafts on the daily 'Benoit' cronjob, only the latest version is found not the previous ones... The IETFDraft.json therefore only contains information about latest IETF drafts and adopted RFC.
We could re-run the analysis script on ALL IETF drafts even if expired (125 774 files) but it may well take more time that the daily run (1686 files)... Possibly the only way to rebuild the right data (+ historical data BTW)

**Comment by miroslavKovacPantheon** [comment]
@evyncke not entirely only way. if we reuse that script to run only on modules that are missing this piece of information and it would be able to find it by itself. Right now it search for that in private json. if it s not there then it is not set at all. this way we have several modules with missing Document name. is there a way to search through those (125774) files to find just specific module with specific revision?

If this is something we are able to do then we can do much more then just retrieve missing information. we can go back historicaly with each module up to when it was created and add all the revisions with correct metadata. then the semver would have much better usability too..

**Comment by miroslavKovacPantheon** [comment]
We have retrieved all the ietf data historicaly and all the data are retrieved
