### ISSUE TITLE
Move functionality into resolver classes

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/backend#531]
In parseAndPopulate pipeline create resolver class for each module property (e.g: RevisionResolver, SchemaResolver, DescriptionResolver...). 
Each class will have resolve() method which will be called for each resolver.
- This will allow to create list of resolvers and resolve and certain amount of module properties.
- It should improve readability and testability of individual module properties
- Some resolvers also might run in parallel -> in case that properties are not dependent on each other

**List of resolvers:**
- [x] belongs-to
- [x] contact
- [x] description
- [x] generated-from
- [x] imports or dependencies
- [x] module-type
- [x] namespace
- [x] organization
- [x] prefix
- [x] reference
- [x] revision
- [x] semantic-version
- [x] submodule
- [x] yang-version

**Comment by richardzilincikPantheon** [comment]
Sure, readability and testability could still benefit from this.

**Comment by SlavomirMazurPantheon** [comment]
Done
