### ISSUE TITLE
Unneccesary file searching

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/backend#538]
When a module imports another module without specifying a revision, it is undefined which revision is used. In order to have consistent results, we currently use a `find_first_file()` function to search specific directories in a specific order, and return the first revision of the imported module it encounters.
A simpler and, in my opinion, more sensible approach, would be always use the latest available revision when the revision is unspecified.
`find_first_file()` also returned the file's location, which is used in constructing a link to it's schema. Instead, we could maintain a dictionary of `<name>@<revision> : <schema_link>` pairs, which can be referenced instead of repeatedly constructing the link on demand.

**Comment by SlavomirMazurPantheon** [comment]
Basic setup for running tests together with several tests is now created. I'm closing this issue, for other scripts that should be covered by the tests create new Github issue with name: `Create tests for <script_name>.py script`
