### ISSUE TITLE
Check compatibility of YCCLIENT with YC.O recent API

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/backend#551]
During an IETF Hackhathon, Ebben Aries ( @earies ) has developed a CLI access to the YC.O via the API: see https://github.com/earies/ycclient

This issue is to check whether it still works with all the recent API changes in the YC.O and in a second step proposes a PR to Ebben to ensure compatibility.

**Comment by richardzilincikPantheon** [comment]
Hello, I've downloaded and tested the client, and it seems to be working.
I've also checked the source code to make sure, and the client only acceses two endpoints: `api/search/modules/<name>,<revision>,<organization>` and `api/contributors`. These, as well as most of the documented API, have been stable for a while, so there shouldn't be any changes needed to the client.

**Comment by evyncke** [comment]
Thank you.

Would it be possible to include this test in your test suite ?

**Comment by richardzilincikPantheon** [comment]
We already have tests in place to make sure the payload these endpoints return is in the correct format, so as long as the client stays unchanged, it will continue to work.
It would be possible to test the client itself against yangcatalog to make sure any incompatible changes to the client are caught.

**Comment by evyncke** [comment]
This is indeed a good idea to add the ycclient in the regression testing.

**Comment by richardzilincikPantheon** [comment]
After having another look at this, it doesn't really seem practical to add ycclient tests to yang catalog's test suite.

We could build some basic ycclient tests and create a PR adding them to ycclients repository.

However I don't really see the utility in this. As I mentioned, yang catalog API endpoints are already covered with tests, so any backward incompatibilities coming from yang catalog's side already get caught. The only way there could be breakage, is if ycclient made a change that didn't conform to the API, and ycclient doesn't seem to be under active development. If you agree, this issue can be closed.

If you believe these tests would be useful to future ycclient development, we can go through with them.

**Comment by SlavomirMazurPantheon** [comment]
We tagged the tests that test the endpoints to which YCCLIENT sends requests.
If there will be any change in these tests, we also will test YCCLIENT again.
