### ISSUE TITLE
Always specify exception type

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/backend#576]
In try-except, exception type should be always specified.
From the [PEP-8](http://www.python.org/dev/peps/pep-0008/) Style Guide for Python :
`When catching exceptions, mention specific exceptions whenever possible instead of using a bare except: clause.`
For example, use:
```
try:
  print(x)
except NameError:
  print('Variable x is not defined')
```
instead of bare `exception:`
```
try:
  print(x)
except:
  print('An exception occurred')
```
This task should be completed in two steps/phases:
- [X] Replace `exception:` at least with `exception Exception:`
- [ ] Define specific exceptions - if not sure which type of exception to use try to think whether exception is necessary of think about using `finally`

It would also be beneficial to use logger.exception() in Exception block (if logger available) to log the exception properly.

**Comment by Fagtoy** [comment]
We specified the exception types where it's possible to understand what type of exception can be expected, in some cases, it's not possible to specify all the expected exception types, so it should stay as ```except Exception```. I close the issue as complete
