### ISSUE TITLE
YANG catalog impact analysis can include outdated dependencies?

### ISSUE THREAD

**Issue by wlupton** [YangCatalog/backend#604]
I went to https://datatracker.ietf.org/doc/draft-boydseda-ipfix-psamp-bulk-data-yang-model and clicked the "Yang impact analysis" link (shouldn't that be "YANG"?).

This took me to https://yangcatalog.org/yang-search/impact_analysis/?show_dir=both&recursion=0&show_rfcs=1&modtags=ietf-ipfix-bulk-data-export%402019-10-28.yang%2Cietf-ipfix-packet-sampling%402019-10-28.yang%2Cietf-ipfix%402019-10-28.yang&show_subm=1 (see image pasted below).

I think that some of the dependencies are wrong. The modules are the 02 versions (2019-10-28) but they’re showing ietf-psamp and ietf-bulk-data-export, which were in 01 but not in 02 (and not referenced by the 02 YANG).

![Screenshot 2019-11-14 at 12 20 00](https://user-images.githubusercontent.com/8874729/68856705-1ba9bc80-06d9-11ea-9df5-c7e97b0ceb31.png)

**Comment by richardzilincikPantheon** [comment]
Hello, this looks like intended behavior.
`ietf-psamp` and `ietf-bulk-data-export` are displayed as being dependent on (i.e. importing) `ietf-ipfix`, not being it's dependencies (note the direction of the arrow), so they wouldn't have to be referenced by modules from the 02 draft to show up. You can turn this off with the "dependents" check box.
`ietf-psamp` didn't specify a revision when importing `ietf-pfix`, so it's undefined which revision would be used, and we can't just pin it as the revision from 01 of the draft. It will continue to show up as a dependent on all revisions of `ietf-ipfix`.
