### ISSUE TITLE
Wrong path while storing hashes

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/backend#609]
There is a wrong path stored in the file which keeps hashes:
```
  "/var/yang/all_modules/huawei-bgp-evpn@2020-04-07.yang": {
    "atn-980b": "f102561c1ea0a7f884dd21754a7d83b34e07f5aa7358ca52531d30a9d022eabf"
  },
  ```
When parsing vendor modules like `Huawei` path is pointing to `/var/yang/all_modules` instead of actual directory from which were the modules parsed.

**Comment by SlavomirMazurPantheon** [comment]
Problem is if a module with the same name and revision is located in the same platform (`atn-980b`) but has different software-versions `V300R005C00SPCa00` `V800R021C00`.

**Comment by richardzilincikPantheon** [comment]
I think you're right, this is a bug. Including the software version in the key looks like a good solution for now. Something to look into later would be to find a way to avoid parsing the whole module just to add implementations. I'll create a separate issue for that.

**Comment by richardzilincikPantheon** [comment]
If we do change the key to `platform/software_version`, the cache will have to be deleted when this is deployed. Would that be an issue @SlavomirMazurPantheon? The populate script will initially take longer than usual, but otherwise it should be fine.

**Comment by SlavomirMazurPantheon** [comment]
Sure no problem.
