### ISSUE TITLE
Github Actions tests broken

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/backend#643]
```
E   ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject
```
Appears on all runs in the last few days. Seems to work locally for me. Maybe updating `gevent` will solve this, but I don't know what triggered this since the version hasn't been changed in 2 years and no relevant packages have been updated recently.

**Comment by richardzilincikPantheon** [comment]
Looks like [this issue](https://github.com/python-greenlet/greenlet/issues/178) which was triggered by incompatible `gevent` and `greenlet` versions, but we don't specify the version of `greenlet`.

**Comment by SlavomirMazurPantheon** [comment]
Same change required also in yangvalidator repo: https://github.com/YangCatalog/yang-validator-extractor/pull/121
