### ISSUE TITLE
API requires dateutil

### ISSUE THREAD

**Issue by sleinen** [YangCatalog/backend#65]
I'm trying to build Docker images for the backend services. When trying to run the API service form a Docker image built using a trivial Dockerfile, I got the following error message:

```
Traceback (most recent call last):
  File "/backend/backend/api/receiver.py", line 48, in <module>
    from parseAndPopulate.modulesComplicatedAlgorithms import ModulesComplicatedAlgorithms
  File "/backend/lib/python3.7/site-packages/yang-0.0.20190323.post932-py3.7.egg/parseAndPopulate/modulesComplicatedAlgorithms.py", line 32, in <module>
    import dateutil.parser
ModuleNotFoundError: No module named 'dateutil'
```

Possible (alternative) solutions include:

1. Add `python-dateutil` to `requirements.txt`
1. Change the code to no longer use `dateutil`—according to @miroslavKovacPantheon, most of the code has already been converted to use `datetime`, but there are still some parts that haven't.

**Comment by miroslavKovacPantheon** [comment]
Actually I still needed the dateutil. I cleaned up imports and updated requiremets file. I have updated requirements.txt in commit above
