### ISSUE TITLE
Unify functionality for fetching all the modules

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/backend#660]
In following scripts, there is a functionality, which send GET request to `search/modules` to retrieve all modules in YANG Catalog.
- parseAndPopulate/modulesComplicatedAlgorithms.py
- parseAndPopulate/resolve_expiration.py
- parseAndPopulate/reviseSemver.py
- recovery/elkFill.py
- sandbox/check_schema.py
- statistic/statistics.py
- utility/revise_tree_type.py

It is done a little differently in each script, so it would be nice to move it into some class and reuse in all scripts.
Create `class ModuleFetcher` which will be stored in new directory called `services`.
In this class there should be `__init__()` method for loading necessary values from config and `fetch_modules()` method with fetching modules from the backend. It should be checked whether request was successful, and if not it should try again for 5 times with 30 seconds intervals.

Also cover functionality with unittests.

**Comment by richardzilincikPantheon** [comment]
Is there any advantage here to creating a class instead of a stand alone function? If there's only one method and it's only ever expected to be called once, I think making a function would be more appropriate.

**Comment by SlavomirMazurPantheon** [comment]
Sure you are right, function should be enough.
