### ISSUE TITLE
Potential mismatch status between the datatracker and yangcatalog

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#67]
Datatracker validates the YANG modules, when the draft is posted.
It might happen that:
1. there are dependencies between drafts, which implies that the YANG validation might fail
2. there are missing dependencies, such as IEEE YANG module, that are missing. So the YANG validation might fail

YANGcatalog runs the validation as a cron job, daily with all dependencies.
So we can better trust the YANG catalog status. 
On a daily basis, it might be for the datatracker to point to the yangcatalog.org validation.

**Comment by miroslavKovacPantheon** [comment]
Is the datatracker using yangvalidator API? Because if yes This issue would be solved since yangvalidator has implemented API that returns json with all the validations.
