### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/backend#68]
Some of the modules have metadata written incorrectly which causes our confd database to refuse this module to be saved. as na example pyang would parse module revision with 2017-5-10 which is incorrect according to iso format. it should be 2017-05-10. and confd is strict about format of the data and is refusing this. we need to be able to save this module with error information that could be solved later. This way Yang search will not give us error that yang module is missing but will show us problem with that file. We need to be adding each file separately to the cond and not as a big json batch of the several 100 of modules.

**Comment by richardzilincikPantheon** [comment]
This issue has been resolved.
Patching modules to Confd falls back to patching one by one in case of an error: [here](https://github.com/YangCatalog/backend/blob/01cb6be8bb281fce84cafd51e2c943e46067f8c3/utility/confdService.py#L77).
Modules are pushed to Redis regardless of if Confd returns an error: [here](https://github.com/YangCatalog/backend/blob/01cb6be8bb281fce84cafd51e2c943e46067f8c3/parseAndPopulate/populate.py#L226) and [here](https://github.com/YangCatalog/backend/blob/01cb6be8bb281fce84cafd51e2c943e46067f8c3/parseAndPopulate/modulesComplicatedAlgorithms.py#L122).
@SlavomirMazurPantheon I think this issue can be closed.
