### ISSUE TITLE
Pushing HTML files into YangModels/yang

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/backend#707]
https://github.com/YangModels/yang/pull/1356/files#diff-5392424194f980e1cdad7a1a733957a020e06bdd949d81dc9244d88f0bbadfc5

The backend seems to somehow be pushing YC HTML files to this repo and overwriting yang files.

**Comment by Fagtoy** [comment]
I close this issue as a duplicate of this one: https://github.com/YangCatalog/backend/issues/698
The problem itself was in this function: https://github.com/YangCatalog/backend/blob/develop/ietfYangDraftPull/draftPullUtility.py#L167
it gets html in response if the module isn’t in our files yet

**Comment by Fagtoy** [comment]
Closing

**Comment by richardzilincikPantheon** [comment]
Oh yeah, sorry, missed that.
