### ISSUE TITLE
Script to populate ETSI modules

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/backend#719]
Create cronjob which will run once a week script with name `etsi_populate.py` placed in `populate_triggers` directory which will clone/fetch content of the following repositories:
- https://forge.etsi.org/rep/qkd/gs018-orch-int-sdn
- https://forge.etsi.org/rep/qkd/gs015-ctrl-int-sdn
- https://forge.etsi.org/rep/nfv/SOL006
and run populate script over them

Overall principle is very similar to the draftPullLocal.py or openconfigPull.py scripts

**Comment by richardzilincikPantheon** [comment]
Do we also want to use these repos for `module-compilation`?
