### ISSUE TITLE
Fix organizations set for mef modules

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/backend#733]
Because ~~iana and~~ mef were missing from our predefined list of organizations, some modules that should have been assigned these organizations now have incorrect organizations.
We could use a script to reparse the organizations for all modules to fix this.
Since there are relatively few modules belonging to these organizations, perhaps this could also be done manually.

**Comment by bclaise** [comment]
IANA is not an organization, it should be IETF, no?

**Comment by richardzilincikPantheon** [comment]
We don't have a super specific definition of what constitutes an organization, and IANA modules do specify "IANA" as the organization, for example
```
module iana-bfd-types {
  yang-version 1.1;
  namespace "urn:ietf:params:xml:ns:yang:iana-bfd-types";
  prefix iana-bfd-types;

  organization
    "IANA";
...
```
But we can set the organization for these modules to IETF (that's the way it is now, there were just some internal inconsistencies that made me think this was unintentional) if that's what you'd expect. Would you prefer we keep them marked as IETF then?

**Comment by richardzilincikPantheon** [comment]
Okay, thank you, we'll leave it that way then.
