### ISSUE TITLE
reviseSemver.py script crashing

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/backend#752]
```
error /var/yang/all_modules/huawei-fim-ifmtrunk@2020-02-28.yang: [Errno 2] No such file or directory: '/var/yang/all_modules/huawei-fim-ifmtrunk@2020-02-28.yang'
```
Such a module really doesn't exist, however there is one with a revision of `2020-02-29`. There's likely more instances of this, the data needs to be corrected with the real revision of the module.

**Comment by dmytro-kyrychenko** [comment]
fixed by changing corrupted data on the production server
