### ISSUE TITLE
POSTMAN collection is down

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#78]
I tried the "Check semantic difference for same module with different revision" POSTMAN collection. The result is:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by miroslavKovacPantheon** [comment]
Check semantic version and search-filter was fixed. The collection was tested today 23.8.2019 and all is working. Closing the issue
