### ISSUE TITLE
Impact analysis isn't always finding modules

### ISSUE THREAD

**Issue by wlupton** [YangCatalog/backend#789]
Here's a case that doesn't currently work for me.

## `bbf-fast` shows as a valid module and can be selected

<img width="328" alt="Screenshot 2023-06-22 at 11 54 03" src="https://github.com/YangCatalog/backend/assets/8874729/593b64b3-71ce-4c32-97f8-c5df87497bc8">

## But there are warnings when loading it

*Question: Why can't the warnings be shown in the main screen rather than having to click to see them in a popup?*

<img width="447" alt="Screenshot 2023-06-22 at 11 54 19" src="https://github.com/YangCatalog/backend/assets/8874729/ed821f17-a5ba-4b8c-a36f-ce1e6dd0d21b">

## It hasn't been found

<img width="199" alt="Screenshot 2023-06-22 at 11 54 27" src="https://github.com/YangCatalog/backend/assets/8874729/7802c211-2633-418e-91a0-0a4d2a4b41ca">

**Comment by richardzilincikPantheon** [comment]
Possibly related to https://github.com/YangCatalog/backend/issues/786, needs more investigation.
> Question: Why can't the warnings be shown in the main screen rather than having to click to see them in a popup?

In some cases the number of warning could be quite large and take up too much screen space.

**Comment by wlupton** [comment]
> In some cases the number of warning could be quite large and take up too much screen space.

You could put them in a scrolling window (scroll bar to appear once there are more than ~5 entries)?

**Comment by richardzilincikPantheon** [comment]
This appears to be a problem with how we handle modules that don't have any "interesting" nodes, 
https://github.com/BroadbandForum/yang/blob/master/standard/interface/bbf-fast.yang for example is just includes and some metadata.
If you happen to have more cases of this issue, please share so we can confirm this is indeed the root cause.

> You could put them in a scrolling window (scroll bar to appear once there are more than ~5 entries)?

Yes, that could also work.

**Comment by dmytro-kyrychenko** [comment]
Okay, so we have found the root cause of this behaviour. We use elasticsearch when looking for revisions of a module and in this case we are hitting the maximum number of results. We are working on a fix right now, that will change es index from which we get revision information
