### ISSUE TITLE
Failed job

### ISSUE THREAD

**Issue by wlupton** [YangCatalog/backend#810]
Please could you check the status of this job, which both succeeded and failed?! Thanks.

```
{
    "info": {
        "job-id": "02270713-d11e-4207-b02d-5ea04e558350",
        "reason": "Failed",
        "result": "Finished successfully"
    }
}
```

**Comment by wlupton** [comment]
Oh, I wonder whether the problem could be that the new modules have a revision date of 2023-12-15, i.e., two days in the future? This was the originally-planned publication date but in fact I published them yesterday.

If this might be the problem, please let me know, and I'll retry on Friday.

**Comment by dmytro-kyrychenko** [comment]
Hello, yes most probably the problem is the future revision date. Please, try it again on the day of the revision and if the problem persists, please, contact us.

**Comment by wlupton** [comment]
Thanks. Will do. Will there at some point be fuller information in the `reason` and `result` fields?

**Comment by dmytro-kyrychenko** [comment]
From 2024 there will be new team working on this project, so you can create github issue with suggestion to add this feature and they might implement it later

**Comment by wlupton** [comment]
I'm afraid this is still failing. I tried twice (see below). Please can you check the failure reason(s)? Thanks.

```
{
  "info": {
    "job-id": "e07cb77d-38bb-4b69-8f62-c3d9109a80ca",
    "reason": "Failed",
    "result": "Finished successfully"
  }
}
```

```
{
  "info": {
    "job-id": "16c5d5e6-1072-460a-aa83-6303af6e8d5d",
    "reason": "Failed",
    "result": "Finished successfully"
  }
}
```

**Comment by dmytro-kyrychenko** [comment]
Could you please, perhaps, send us more details about this job, so we could try to recreate it by ourselves?

**Comment by wlupton** [comment]
Here's the command (omitting the `-u` credentials) using the attached [metadata.json](https://github.com/YangCatalog/backend/files/13705327/metadata.json). Thanks.

```
curl --http1.1 -H 'Content-Type: application/json' -X PUT \
    -d @metadata.json https://yangcatalog.org/api/modules
```
