### ISSUE TITLE
Yang Catalog frontend showing bad links

### ISSUE THREAD

**Issue by rbu9fe** [YangCatalog/backend#812]
I used to work with Yang Catalog a few weeks ago and everything worked fine. Now suddenly the links to Yang schemas and trees are broken. For example, https://www.yangcatalog.org/yang-search/module_details/ietf-inet-types now provides link to `localhost`:
- schema: http://localhost/all_modules/ietf-inet-types@2013-07-15.yang
- yang-tree: http://localhost/api/services/tree/ietf-inet-types@2013-07-15.yang

Furthermore, many previously existing Yang models can't be found anymore, e.g. all starting with `ieee` like `ieee802-types`.

**Comment by xorrkaz** [comment]
This has been fixed.  The solution was updating the config file for the new YC.o deployment to reflect production rather than test.  Thanks for the report.
