### ISSUE TITLE
Catalog upload apparently worked but didn't return a JSON job description

### ISSUE THREAD

**Issue by wlupton** [YangCatalog/backend#815]
I did what I usually do:
```
% curl --http1.1 -u wlupton:PASSWORD \
    -H 'Content-Type: application/json' \
    -X PUT -d @metadata.json \
    https://yangcatalog.org/api/modules >metadata.out
```

It apparently succeeded:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 56  227k    0     0   56  128k      0   839k --:--:-- --:--:-- --:--:--  977k
```

but `metadata.out` is empty:
```
% ls -l metadata.out 
-rw-r--r--  1 william  staff  0 19 Jan 16:44 metadata.out
```

I can share `metadata.json` if that would help. It starts like this:
```
{
  "modules": {
    "module": [
      {
        "author-email": "help@broadband-forum.org",
        "document-name": "TR-477: Cloud CO Enhancement - Access Node Functional Disaggregation <https://www.broadband-forum.org/technical/download/TR-477.pdf>",
        "generated-from": "not-applicable",
        "maturity-level": "ratified",
        "module-classification": "network-element",
        "name": "bbf-d-olt-dhcpra",
        "organization": "bbf",
        "reference": "https://www.broadband-forum.org/technical/download/TR-477.pdf",
        "revision": "2024-01-19",
        "source-file": {
          "owner": "BroadbandForum",
          "path": "standard/application/bbf-d-olt-dhcpra.yang",
          "repository": "yang"
        }
      },
```

Any ideas? Thanks.

**Comment by wlupton** [comment]
I have checked that the `bbf-d-olt-dhcpra` module isn't in the catalog, so I think that the upload failed (rather than just completing silently).

I just retried the upload, with the same behaviour as first time.

Any thoughts?

**Comment by rjsparks** [comment]
@wlupton please try that request again using https://www.yangcatalog.org/api/modules

**Comment by wlupton** [comment]
Aha!

```
{"info":"Verification successful","job-id":"94f8cf0c-d924-44f3-9591-c9112f5748e6"}
```

and the job shows as being in progress:

```
% make metadata-check 
{
  "info": {
    "job-id": "94f8cf0c-d924-44f3-9591-c9112f5748e6",
    "reason": "",
    "result": "In progress"
  }
}
```

and now as being done (but failed?):

```
% make metadata-check 
{
  "info": {
    "job-id": "94f8cf0c-d924-44f3-9591-c9112f5748e6",
    "reason": "Failed",
    "result": "Finished successfully"
  }
}
```

I checked to see whether `bbf-d-olt-dhcpra` is now in the catalog but it isn't... might there be an expected delay before it shows up?

**Comment by wlupton** [comment]
I also used the API to check for `bbf-d-olt-dhcpra`. Is it expected that it's so slow? Determining that the module doesn't exist took 18s!

<img width="717" alt="Screenshot 2024-02-22 at 19 38 36" src="https://github.com/YangCatalog/backend/assets/8874729/ca82451e-1f5b-49fd-9742-0973c24f614a">

**Comment by xorrkaz** [comment]
<img width="1054" alt="Screenshot 2024-02-26 at 08 38 55" src="https://github.com/YangCatalog/backend/assets/9667809/2c3b2e55-99b9-46b1-88ec-6b099af9d9d3">

YC.o should be back at full-strength now.  Your module is there.

**Comment by wlupton** [comment]
Thanks! Looks great.

**Comment by wlupton** [comment]
Oh, @xorrkaz, was this contradictory message expected?

```
% make metadata-check 
{
  "info": {
    "job-id": "94f8cf0c-d924-44f3-9591-c9112f5748e6",
    "reason": "Failed",
    "result": "Finished successfully"
  }
}
```

**Comment by xorrkaz** [comment]
Looking back at the logs, there was an issue (transient, I think) connecting to the SMTP server within the container that runs the job.  This caused the async job to yield a Failed reason code.  I can't see how that would be systemic.  But if you run a new job, I can watch the logs in real time to see if there still is an issue.

**Comment by wlupton** [comment]
Thanks. I just kicked off this one.
```
% make metadata-check
USERNAME = master (override)
{
  "info": {
    "job-id": "44772a35-26d8-4496-88a3-a177139bdd04",
    "reason": "",
    "result": "In progress"
  }
}
```

**Comment by wlupton** [comment]
OK...
```
{
  "info": {
    "job-id": "63a2b39a-fa30-4511-be0e-62af24883f91",
    "reason": "",
    "result": "In progress"
  }
}
```

**Comment by xorrkaz** [comment]
Progress is definitely being made this time.  I think I licked that first bug at least.

**Comment by xorrkaz** [comment]
FYI, I created YangCatalog/deployment#208 for this.

**Comment by wlupton** [comment]
```
{
  "info": {
    "job-id": "a04df5b2-3da6-4989-8081-6754013ff625",
    "reason": "",
    "result": "In progress"
  }
}
```

**Comment by xorrkaz** [comment]
Excellent!  All issues are fixed in the PR.
