### ISSUE TITLE
api results return localhost urls

### ISSUE THREAD

**Issue by rjsparks** [YangCatalog/backend#829]
Reported by Fabrice Blanche:

https://yangcatalog.org/api/search/modules/ietf-yang-types,2013-07-15,ietf

returns json containing urls that look like:
```
http://localhost/all_mod…ng-types@2013-07-15.yang
```
where it should be pointing to yangcatalog.org instead.

**Comment by xorrkaz** [comment]
This _one_ is fixed.  Unfortunately to fix all of them, one needs to do redis surgery.  Let me think about how to automate this.

**Comment by xorrkaz** [comment]
Should all be fixed now.
